name: pulsequeue
region: nyc
services:
  - name: api
    github:
      repo: MarcHe124/digitalocean
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: AUTO_START_WORKER
        value: "false"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: WORKER_CONCURRENCY
        value: "2"
      - key: DEFAULT_MAX_RETRIES
        value: "3"
      - key: DEFAULT_TIMEOUT_SECONDS
        value: "5"
      - key: MAX_TIMEOUT_SECONDS
        value: "60"
      - key: WORKER_LEASE_GRACE_SECONDS
        value: "15"
      - key: LEASE_REAPER_INTERVAL_SECONDS
        value: "5"
      - key: SCHEDULER_INTERVAL_SECONDS
        value: "1"
      - key: CONFIG_SYNC_INTERVAL_SECONDS
        value: "1"
workers:
  - name: worker
    github:
      repo: MarcHe124/digitalocean
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    run_command: python -m app.worker
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: WORKER_CONCURRENCY
        value: "2"
      - key: DEFAULT_MAX_RETRIES
        value: "3"
      - key: DEFAULT_TIMEOUT_SECONDS
        value: "5"
      - key: MAX_TIMEOUT_SECONDS
        value: "60"
      - key: WORKER_LEASE_GRACE_SECONDS
        value: "15"
      - key: LEASE_REAPER_INTERVAL_SECONDS
        value: "5"
      - key: SCHEDULER_INTERVAL_SECONDS
        value: "1"
      - key: CONFIG_SYNC_INTERVAL_SECONDS
        value: "1"
databases:
  - name: db
    engine: PG
    version: "17"
    production: false
